repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9  # Uppdatera till den senaste versionen från https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
      - id: ruff        # Kör ruff check --fix
      - id: ruff-format # Kör ruff format